version: 2
formats:
  - htmlzip
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    
conda:
  environment: docs/environment-docs.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: True
