name: grits
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - gsd=2.9
  - mbuild
  - ele
  - freud
  - openbabel
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - rdkit
